#### ============================================
###  1. Import Libraries
#### ============================================

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### ============================================
###  2. Read a Data
#### ============================================

In [3]:
Data = pd.read_csv("/Users/mac/Desktop/Zain Projects/Task 2 Visitor Mall Dataset/data/raw/total_visitors_per_mall.csv")

#### ============================================
###  3. Check a Data
#### ============================================

In [4]:
Data.head()

,SUBSCRIBER_ID,VISIT_DATE,MALL_NAME,HOME_GOVERNORATE,WORK_GOVERNORATE,NATIONALITY,ARPU_BRACKET,DEVICE_OS,AGE_BRACKET,GENDER,STUDENT,IS_EMPLOYEE,CREDIT_CATEGORY,YEAR,MONTH,DAY,Day,TIME_DIFF
0,11121,2022-11-08 13:18:15,Sunset Mall,Governorate 1,Governorate 1,Citizen,Low,iOS,> 25 and <= 45,Female,Not a student,0,Fair,2022,2022-11,8,8,NaN
1,11122,2022-11-19 15:28:46,City Center Mall,Governorate 2,Governorate 2,Citizen,High,iOS,> 25 and <= 45,Male,Not a student,0,Excelent,2022,2022-11,19,19,NaN
2,11122,2022-11-04 11:44:39,Sunset Mall,Governorate 2,Governorate 2,Citizen,High,iOS,> 25 and <= 45,Male,Not a student,0,Excelent,2022,2022-11,4,4,NaN
3,11123,2022-11-05 14:52:57,City Center Mall,Governorate 1,Governorate 1,Citizen,Low,iOS,<= 18,Male,Not a student,0,Excelent,2022,2022-11,5,5,NaN
4,11124,2022-11-07 17:43:37,Oasis Mall,Governorate 2,Governorate 2,Citizen,High,iOS,> 45,Male,Not a student,0,Excelent,2022,2022-11,7,7,NaN

In [5]:
Data.tail()

,SUBSCRIBER_ID,VISIT_DATE,MALL_NAME,HOME_GOVERNORATE,WORK_GOVERNORATE,NATIONALITY,ARPU_BRACKET,DEVICE_OS,AGE_BRACKET,GENDER,STUDENT,IS_EMPLOYEE,CREDIT_CATEGORY,YEAR,MONTH,DAY,Day,TIME_DIFF
899531,378366,2022-11-15 19:14:14,Century mall,Governorate 1,Governorate 1,Citizen,High,Android,> 45,Male,Not a student,0,Excelent,2022,2022-11,15,15,NaN
899532,378366,2022-11-27 15:05:58,Century mall,Governorate 1,Governorate 1,Citizen,High,Android,> 45,Male,Not a student,0,Excelent,2022,2022-11,27,27,283.432500
899533,378366,2022-11-24 14:14:29,City Center Mall,Governorate 1,Governorate 1,Citizen,High,Android,> 45,Male,Not a student,0,Excelent,2022,2022-11,24,24,NaN
899534,378366,2022-11-24 21:24:54,City Center Mall,Governorate 1,Governorate 1,Citizen,High,Android,> 45,Male,Not a student,0,Excelent,2022,2022-11,24,24,6.883889
899535,378366,2022-11-25 11:49:57,City Center Mall,Governorate 1,Governorate 1,Citizen,High,Android,> 45,Male,Not a student,0,Excelent,2022,2022-11,25,25,14.417500

In [6]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899536 entries, 0 to 899535
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   SUBSCRIBER_ID     899536 non-null  int64
 1   VISIT_DATE        899536 non-null  object
 2   MALL_NAME         899536 non-null  object
 3   HOME_GOVERNORATE  899536 non-null  object
 4   WORK_GOVERNORATE  899536 non-null  object
 5   NATIONALITY       899536 non-null  object
 6   ARPU_BRACKET      899536 non-null  object
 7   DEVICE_OS         899536 non-null  object
 8   AGE_BRACKET       899536 non-null  object
 9   GENDER            899536 non-null  object
 10  STUDENT           899536 non-null  object
 11  IS_EMPLOYEE       899536 non-null  int64
 12  CREDIT_CATEGORY   899536 non-null  object
 13  YEAR              899536 non-null  int64
 14  MONTH             899536 non-null  object
 15  DAY               899536 non-null  int64
 16  Day               899536 non-null  int64
 17  TIME_DIFF         391879 non-null  float64
dtypes: float64(1), int64(5), object(12)
memory usage: 123.5+ MB

#### ============================================
###  4. Check a null Data and Duplicate
#### ============================================

In [7]:
Data.isnull().sum()

SUBSCRIBER_ID            0
VISIT_DATE               0
MALL_NAME                0
HOME_GOVERNORATE         0
WORK_GOVERNORATE         0
NATIONALITY              0
ARPU_BRACKET             0
DEVICE_OS                0
AGE_BRACKET              0
GENDER                   0
STUDENT                  0
IS_EMPLOYEE              0
CREDIT_CATEGORY          0
YEAR                     0
MONTH                    0
DAY                      0
Day                      0
TIME_DIFF           507657
dtype: int64

In [8]:
Data.duplicated().sum()

0

#### ============================================
###  5. Cleaning a Dataset
#### ============================================

###  5.1 Drop a TIME_DIFF Column

In [10]:
Data.drop(columns=['TIME_DIFF'], inplace=True)

###  5.2 Drop a Day Column

In [11]:
Data.drop(columns=['Day'], inplace=True)

###  5.3 Drop a Month Column

In [17]:
Data.drop(columns=['MONTH'], inplace=True)

###  5.4 Treatment a Words inside a Colmuns

In [13]:
Data['CREDIT_CATEGORY'] = Data['CREDIT_CATEGORY'].replace('Excelent', 'Excellent')

In [18]:
Data.isnull().sum()

SUBSCRIBER_ID       0
VISIT_DATE          0
MALL_NAME           0
HOME_GOVERNORATE    0
WORK_GOVERNORATE    0
NATIONALITY         0
ARPU_BRACKET        0
DEVICE_OS           0
AGE_BRACKET         0
GENDER              0
STUDENT             0
IS_EMPLOYEE         0
CREDIT_CATEGORY     0
YEAR                0
DAY                 0
dtype: int64

#### ============================================
###  6. Save a Cleaning Data
#### ============================================

In [19]:
Data.to_csv('total_visitors_per_mall_cleaned.csv', index=False)